// Application 
const SET_INITIAL_STATE_RESP = 'SET_INITIAL_STATE_RESP';
const TEXT_CHANGED = 'TEXT_CHANGED';
const TAB_CHANGED = 'TAB_CHANGED';

// Latest News 
const LATEST_NEWS_SUCCESS  = 'LATEST_NEWS_SUCCESS';

// Company Overview 
const COMPANY_OVERVIEW_SUCCESS = 'COMPANY_OVERVIEW_SUCCESS';

// Top Peers
const TOP_PEERS_SUCCESS = 'TOP_PEERS_SUCCESS';

// Key Stats 
const KEYSTATS_SUCCESS = 'KEYSTATS_SUCCESS';

// Stock Chart 
const STOCK_CHART_SUCCESS = 'STOCK_CHART_SUCCESS';
const STOCK_FREQUENCY_SUCCESS = 'STOCK_FREQUENCY_SUCCESS';
const PRICE_CHART_WRAPPER_SUCCESS = 'PRICE_CHART_WRAPPER_SUCCESS';
const FREQ_CHANGE_SELECTED = 'FREQ_CHANGE_SELECTED'; 


export { SET_INITIAL_STATE_RESP, TEXT_CHANGED, TAB_CHANGED, 
    LATEST_NEWS_SUCCESS, COMPANY_OVERVIEW_SUCCESS, TOP_PEERS_SUCCESS, 
    KEYSTATS_SUCCESS, STOCK_CHART_SUCCESS, STOCK_FREQUENCY_SUCCESS,
    PRICE_CHART_WRAPPER_SUCCESS, FREQ_CHANGE_SELECTED };