// Application 
const SET_INITIAL_STATE_RESP = 'SET_INITIAL_STATE_RESP';
const TEXT_CHANGED = 'TEXT_CHANGED';
const TAB_CHANGED = 'TAB_CHANGED';

// Latest News 
const LATEST_NEWS_SUCCESS  = 'LATEST_NEWS_SUCCESS';

export { SET_INITIAL_STATE_RESP, TEXT_CHANGED, TAB_CHANGED, LATEST_NEWS_SUCCESS };