// Application 
const SET_INITIAL_STATE_RESP = 'SET_INITIAL_STATE_RESP';
const TEXT_CHANGED = 'TEXT_CHANGED';
const TAB_CHANGED = 'TAB_CHANGED';

// Latest News 
const LATEST_NEWS_SUCCESS  = 'LATEST_NEWS_SUCCESS';

// Company Overview 
const COMPANY_OVERVIEW_SUCCESS = 'COMPANY_OVERVIEW_SUCCESS';

// Top Peers
const TOP_PEERS_SUCCESS = 'TOP_PEERS_SUCCESS';

export { SET_INITIAL_STATE_RESP, TEXT_CHANGED, TAB_CHANGED, 
    LATEST_NEWS_SUCCESS, COMPANY_OVERVIEW_SUCCESS, TOP_PEERS_SUCCESS };